# Site settings
title: Flack{er}.to Hacker
email: jake.wengroff@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I loved my career in PR and journalism, but it was time for a change.  
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://jakewengroff.github.io" # the base hostname & protocol for your site
twitter_username: JakeWengroff
github_username:  JakeWengroff

# Build settings
markdown: kramdown
